# Generated by Django 4.2.1 on 2023-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='choi_public',
            field=models.CharField(choices=[('New', 'Новость'), ('Art', 'Статья')], default='Art', max_length=3),
        ),
    ]
