# Generated by Django 4.2.1 on 2023-05-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_rename_rating_comment__rating_alter_post_choi_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='_rating',
        ),
    ]
