# Generated by Django 4.2.1 on 2023-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_alter_comment__rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
    ]
